name: Astro Check

on:
  push:
    branches:
      - main

jobs:
  run-astro-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.1.34"

      - name: Install deps
        run: bun install

      - name: Run astro check
        run: bunx --bun astro check
